#!/usr/bin/env bash
# Copies one or more specified Kubernetes secrets from a source context to a
# destination context.

src_ctx="$1"
dest_ctx="$2"
cur_ctx="$(kubectl config current-context)"
secrets=${@:3}

usage() {
	printf "Usage: \e[1m%s\e[0m \e[4mSOURCE\e[0m \e[4mDEST\e[0m \e[4mK8S-SECRET\e[0m...\n" "$(basename ${BASH_SOURCE})"
}

if [[ $# -lt 3 ]]; then
	usage

	exit 1
fi

printf "Current context is \"%s\"\n" "${cur_ctx}"

for s in ${secrets[@]}; do
	kubectl config use-context "${src_ctx}"
	# Remove the namespace info from the secret since we're copying it to a new
	# context.
	src_sec="$(kubectl get secret $s -o yaml | grep -v 'namespace:')"

	kubectl config use-context "${dest_ctx}"
	printf "${src_sec}" |  kubectl apply -f -
done

kubectl config use-context "${cur_ctx}"

exit 0
